django_commander/urls.py
from django.urls import re_path

from django_commander import views


app_name = "django_commander"
urlpatterns = [
    re_path(r"^$", views.home, name="home"),
    re_path(r"^(?P<command_id>.+)$", views.view_command, name="view_command"),
]

testapp/urls.py
from django.conf.urls import include
from django.urls import re_path
from testapp import views


urlpatterns = [
    re_path(r"^login$", views.login, name="login"),
    re_path(r"^logout$", views.logout, name="logout"),
]

urlpatterns += [re_path(r"^commands/", include("django_commander.urls"))]

django_commander/models.py
from builtins import str
from builtins import object
from django.db import models
from django.core.serializers.json import DjangoJSONEncoder
from picklefield.fields import PickledObjectField

from django_pewtils.abstract_models import BasicExtendedModel
from django_pewtils import get_model, consolidate_objects


class LoggedExtendedModel(BasicExtendedModel):

    """
    This abstract model can be used as a base class on any model that you want to track.  All of the commands in
    django_commander (i.e. BasicCommand and everything that inherits from it) are automatically logged in the database
    with a unique Command row that's a combination of the command's name and the parameters passed to it, and when
    a command is run, it is logged with a new row in the CommandLog table.  You can also choose to write your commands
    such that they create associations in the database with objects that they modify.  If those objects inherit from
    LoggedExtendedModel, you can add the command directly (`my_object.command_logs.add(self.log)`) or you can pass
    `self.log` to the `django_pewtils` `create_or_update` function, which will automatically create the association.
    """

    commands = models.ManyToManyField(
        "django_commander.Command", related_name="%(class)s_related"
    )
    command_logs = models.ManyToManyField(
        "django_commander.CommandLog", related_name="%(class)s_related"
    )

    class Meta(object):

        abstract = True


class Command(BasicExtendedModel):

    """
    Refers to a command class that's used to load data into the database.  Parameters are values used that have a
    bearing on the data that get loaded in, and so the name and parameters, taken together, refer to a specific set of
    data loaded by a specific process.  If your app's models inherit from LoggedExtendedModel, you can use M2M
    relations with CommandLog and Command to track the sources from which a given object's data have been pulled,
    for example.
    """

    name = models.CharField(
        max_length=400, db_index=True, help_text="The name of a command"
    )
    parameters = models.JSONField(
        default=dict,
        help_text="The parameters used to initialize the command",
        encoder=DjangoJSONEncoder,
    )

    class Meta(object):

        unique_together = ("name", "parameters")

    def __str__(self):

        return "%s %s" % (self.name, self.parameters)

    @property
    def command_class(self):

        from django_commander.commands import commands

        return commands[self.name]

    @property
    def command(self):

        return self.command_class(**self.parameters)

    def run(self):

        self.command.run()

    def consolidate_logs(self):

        first = self.logs.order_by("start_time")[0]
        first_time = first.start_time
        last = self.logs.order_by("-start_time")[0]
        last_time = last.start_time
        for extra in self.logs.exclude(pk=last.pk):
            consolidated = consolidate_objects(source=extra, target=last)
        consolidated.start_time = first_time
        consolidated.save()


class CommandLog(BasicExtendedModel):

    """
    A specific log generated by a command, including optional arguments and any errors generated by the command.
    """

    command = models.ForeignKey(
        "django_commander.Command",
        on_delete=models.CASCADE,
        related_name="logs",
        help_text="The parent command",
    )
    start_time = models.DateTimeField(
        auto_now_add=True, help_text="The time at which the command began executing"
    )
    end_time = models.DateTimeField(
        null=True, help_text="The time at which the command finished (if applicable)"
    )
    options = models.JSONField(
        default=dict,
        help_text="The options passed to the command",
        encoder=DjangoJSONEncoder,
    )
    error = PickledObjectField(
        null=True, help_text="The error returned by the command (if applicable)"
    )

    def __str__(self):

        if self.end_time:
            status = "COMPLETED"
        elif self.error:
            status = "FAILED"
        else:
            status = "RUNNING"
        return "%s (pk=%s): %s" % (str(self.command), str(self.pk), status)


from django.db.models.signals import m2m_changed


def update_command_m2m(sender, **kwargs):

    """
    Intercepts the creation of new links between logs and related objects, and also associates those related objects
    with the log's command.

    :param sender:
    :param kwargs:
    :return:
    """

    if kwargs["action"] == "post_add" and "instance" in kwargs and kwargs["instance"]:
        obj = kwargs["instance"]
        if obj._meta.model != CommandLog and (
            LoggedExtendedModel in obj._meta.model.__bases__
        ):
            commands = Command.objects.filter(
                pk__in=obj.command_logs.values_list("command_id", flat=True)
            )
            obj.commands.set(commands)


m2m_changed.connect(update_command_m2m, sender=LoggedExtendedModel.command_logs.through)

django_commander/views.py
import datetime

from django.shortcuts import render
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.conf import settings

from django_commander.models import Command, CommandLog


# @login_required
def home(request):

    commands = []
    for c in Command.objects.all():
        commands.append({"command": c, "latest_log": c.logs.order_by("-start_time")[0]})
    commands = sorted(commands, key=lambda x: x["latest_log"].start_time, reverse=True)

    return render(request, "django_commander/index.html", {"commands": commands})


# @login_required
def view_command(request, command_id):

    command = Command.objects.get(pk=command_id)
    logs = command.logs.order_by("-start_time")[:10]

    return render(
        request, "django_commander/command.html", {"command": command, "logs": logs}
    )

django_commander/templates/django_commander/_template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
        <title>Django Commander</title>

        <link href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>
        <style>
            body {
                padding-top: 60px;
            }
        </style>
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
        <!--[if lt IE 9]>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        {% block extra_head %}{% endblock %}

    </head>

    <body>

        {% block modals %}{% endblock %}

        {% if request.user and request.user.is_authenticated %}
            <nav class="navbar navbar-default navbar-fixed-top">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <div class="navbar-brand"><a href="{% url 'django_commander:home' %}">Django Commander</a></div>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% if request.user %}{{ request.user.coder.name }}{% endif %}<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/">App Home</a></li>
                                    <li><a href="{% url 'logout' %}">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        {% endif %}

        <div class="container">

            {% block menu %}{% endblock %}
            {% block body %}{% endblock %}

        </div>

        <script src="http://d3js.org/d3.v3.min.js"></script>
        <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.0-rc.2/jquery-ui.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.1/knockout-min.js"></script>

        {% block extra_body %}{% endblock %}

    </body>
</html>

django_commander/templates/django_commander/command.html
{% extends "django_commander/_template.html" %}

{% load static %}

{% block extra_head %}{% endblock %}

{% block modals %}{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Ten most recent runs for: {{ command.name }} (
                        {% for k, v in command.command.parameters.items %}
                            {{ k }}: {{ v }},
                        {% endfor %})
                    </h3>
                </div>
                <table class="panel-body table table-condensed">
                    <tr><th>Options</th><th>Start</th><th>End</th><th>Objects</th><th>Error</th></tr>
                    {% for log in logs %}
                        <tr>
                            <td>
                                {% for k, v in log.options.items %}
                                    {{ k }}: {{ v }}<br>
                                {% endfor %}
                            </td>
                            <td>{{ log.start_time }}</td>
                            <td>{{ log.end_time }}</td>
                            <td>
                                {% for model, objs in log.related_objects.items %}
                                    {% if model != 'command' %}
                                        {{ model }}: {{ objs.count }}<br>
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>{{ log.error }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block extra_body %}{% endblock %}

django_commander/templates/django_commander/index.html
{% extends "django_commander/_template.html" %}

{% load static %}

{% block extra_head %}{% endblock %}

{% block modals %}{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Commands</h3>
                </div>
                <table class="panel-body table table-condensed">
                    <tr><th>Command</th><th>Parameters</th><th>Latest Run</th><th></th></tr>
                    {% for command in commands %}
                        <tr>
                            <td>{{ command.command.name }}</td>
                            <td>
                                {% for k, v in command.command.parameters.items %}
                                    {{ k }}: {{ v }}<br>
                                {% endfor %}
                            </td>
                            <td>
                                Start: {{ command.latest_log.start_time }}<br>
                                End: {{ command.latest_log.end_time }}
                            </td>
                            <td>
                                <a class="btn btn-primary" href="{% url 'django_commander:view_command' command.command.pk %}">View</a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block extra_body %}{% endblock %}